// packages/sdui-document/src/blocks/code/blockGuards.ts
// Block-type domain code moved to src/block-types/<name>/ — re-exported here
// to keep the public API (blocks/code barrel) stable.
export type { CalloutBlock, CalloutBlockAttributes } from '../../block-types/callout/callout'
export { isCalloutBlock } from '../../block-types/callout/callout'
export type { ChecklistBlock, ChecklistBlockState } from '../../block-types/checklist/checklist'
export { isChecklistBlock } from '../../block-types/checklist/checklist'
export type { DividerBlock } from '../../block-types/divider/divider'
export { isDividerBlock } from '../../block-types/divider/divider'
export type { FileBlock, FileBlockAttributes } from '../../block-types/file/file'
export { isFileBlock } from '../../block-types/file/file'
export type { HeadingBlock, HeadingBlockState } from '../../block-types/heading/heading'
export { isHeadingBlock } from '../../block-types/heading/heading'
export type { ImageBlock, ImageBlockAttributes } from '../../block-types/image/image'
export { isImageBlock } from '../../block-types/image/image'
export type { LinkBlock, LinkBlockAttributes } from '../../block-types/link/link'
export { isLinkBlock } from '../../block-types/link/link'
export type { ParagraphBlock, ParagraphBlockState } from '../../block-types/paragraph/paragraph'
export { isParagraphBlock } from '../../block-types/paragraph/paragraph'
export { blockText } from '../../block-types/shared'
